# Homework 6


## EMNIST Dataset

[EMNIST dataset](https://www.nist.gov/itl/iad/image-group/emnist-dataset) is a set of hand-written characters and digits. Each of the data points is a grayscale image of size 28x28 pixels.  The structure of the dataset is the same as the infamous [MNIST](http://yann.lecun.com/exdb/mnist/) dataset, but this dataset contains more samples and also contains characters. You can find more information on the dataset in the paper available at [https://arxiv.org/abs/1702.05373v1](https://arxiv.org/abs/1702.05373v1)

You can find the dataset you need [at this link](https://www.dropbox.com/sh/vgap8ici7xs5w7f/AACE-9RrDpbGCc6bP72gHRfUa?dl=0).  Please download and use your local copy to do the homework.

## Task 1

Ingest the data (both the train and test sets) into this pyhthon notebook as a numpy array.


## Task 2

Write a convolutional artifial neural network model, train it and test it.


## Notes

1. You need to document each of your steps in both the ingestion phase and processing phase: explain the steps taken, the problems you encounter, how you solved them.

2. DO NOT write python classes.  In other words, I do not want to see `__init__` or `__main__` in your code.  They are hard to follow (as they contain mutable state) and hard to port to future code you might write on a similar project.

3. When you upload your solution to github, DO NOT include the datasets. They are large and I already have copies. I can test your models on the copy I have.

## Task 1

First, we need to import required packages.

In [1]:
import numpy as np
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Activation, MaxPooling2D, Flatten

C:\Users\ceren\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


From the code below, the train and test images and labels are imported as numpy array.

In [2]:
from tensorflow.contrib.learn.python.learn.datasets.mnist import extract_images, extract_labels
import os

with open(os.path.expanduser('~/MAT388E/data/EMNIST/emnist-balanced-test-images-idx3-ubyte.gz'), 'rb') as f:
    test_images = extract_images(f)
with open(os.path.expanduser('~/MAT388E/data/EMNIST/emnist-balanced-test-labels-idx1-ubyte.gz'), 'rb') as f:
    test_labels = extract_labels(f)

with open(os.path.expanduser('~/MAT388E/data/EMNIST/emnist-balanced-train-images-idx3-ubyte.gz'), 'rb') as f:
    train_images = extract_images(f)
with open(os.path.expanduser('~/MAT388E/data/EMNIST/emnist-balanced-train-labels-idx1-ubyte.gz'), 'rb') as f:
    train_labels = extract_labels(f)

Instructions for updating:
Please use tf.data to implement this functionality.
Extracting C:\Users\ceren/MAT388E/data/EMNIST/emnist-balanced-test-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting C:\Users\ceren/MAT388E/data/EMNIST/emnist-balanced-test-labels-idx1-ubyte.gz
Extracting C:\Users\ceren/MAT388E/data/EMNIST/emnist-balanced-train-images-idx3-ubyte.gz
Extracting C:\Users\ceren/MAT388E/data/EMNIST/emnist-balanced-train-labels-idx1-ubyte.gz


In [37]:
print('train labels \n',train_labels)
ys = keras.utils.to_categorical(train_labels)
print('\ntrain labels to categorical \n',ys)
print('\ntest labels \n',test_labels)
ys_test = keras.utils.to_categorical(test_labels)
print('\ntest labels to categorical \n',ys_test)

train labels 
 [45 36 43 ... 23 31  8]

train labels to categorical 
 [[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

test labels 
 [41 39  9 ...  1 26 33]

test labels to categorical 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [39]:
print('the number of labels in the train dataset is: ',len(set(train_labels)))
print('the number of labels in the test dataset is: ',len(set(test_labels)))

the number of labels in the train dataset is:  47
the number of labels in the test dataset is:  47


## Task 2

The neural network model is built as follows:

In [45]:
model = Sequential()
model.add(Conv2D(128, (8,8), input_shape=(28,28,1,), activation='softsign'))

In [46]:
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.25))

In [47]:
model.add(MaxPooling2D(pool_size=(3,3)))

In [48]:
model.add(Flatten())
model.add(Dense(47, activation='sigmoid'))

In [50]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='RMSProp')
model.fit(train_images.reshape(112800,28,28,1), ys, batch_size=32, epochs=10, validation_data=(test_images.reshape(18800,28,28,1), ys_test))

Train on 112800 samples, validate on 18800 samples
Epoch 1/10
112800/112800 [==============================] - 343s 3ms/step - loss: 0.5042 - acc: 0.8381 - val_loss: 0.5158 - val_acc: 0.8350
Epoch 2/10
112800/112800 [==============================] - 340s 3ms/step - loss: 0.4907 - acc: 0.8423 - val_loss: 0.4989 - val_acc: 0.8399
Epoch 3/10
112800/112800 [==============================] - 353s 3ms/step - loss: 0.4932 - acc: 0.8429 - val_loss: 0.5027 - val_acc: 0.8421
Epoch 4/10
112800/112800 [==============================] - 358s 3ms/step - loss: 0.4960 - acc: 0.8429 - val_loss: 0.5042 - val_acc: 0.8436
Epoch 5/10
112800/112800 [==============================] - 367s 3ms/step - loss: 0.4971 - acc: 0.8421 - val_loss: 0.5088 - val_acc: 0.8365
Epoch 6/10
112800/112800 [==============================] - 367s 3ms/step - loss: 0.5027 - acc: 0.8419 - val_loss: 0.5188 - val_acc: 0.8349
Epoch 7/10
112800/112800 [==============================] - 368s 3ms/step - loss: 0.5091 - acc: 0.8403 - val_

Accuracy of the model is 83.71% in the train set and 83.31% in the test set. 

In [51]:
result = model.evaluate(test_images.reshape(18800,28,28,1), ys_test, batch_size=32, verbose=1)
result

18800/18800 [==============================] - 15s 789us/step


[0.5202114541987155, 0.8331382978723404]

Summary of the model can be seen in the following table:

In [53]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, 21, 21, 128)       8320      
_________________________________________________________________
dense_11 (Dense)             (None, 21, 21, 64)        8256      
_________________________________________________________________
dropout_5 (Dropout)          (None, 21, 21, 64)        0         
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 7, 7, 64)          0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 3136)              0         
_________________________________________________________________
dense_12 (Dense)             (None, 47)                147439    
Total params: 164,015
Trainable params: 164,015
Non-trainable params: 0
_________________________________________________________________
